/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { VendorCreate } from "../../models/vendor-create";
import { VendorRead } from "../../models/vendor-read";

export interface CreateVendor$Params {
  body: VendorCreate;
}

export function createVendor(
  http: HttpClient,
  rootUrl: string,
  params: CreateVendor$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VendorRead>> {
  const rb = new RequestBuilder(rootUrl, createVendor.PATH, "post");
  if (params) {
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<VendorRead>;
      }),
    );
}

createVendor.PATH = "/api/vendors";
