/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { VendorSpend } from "../../models/vendor-spend";

export interface GetVendorSpend$Params {
  vendor_id: string;
}

export function getVendorSpend(
  http: HttpClient,
  rootUrl: string,
  params: GetVendorSpend$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VendorSpend>> {
  const rb = new RequestBuilder(rootUrl, getVendorSpend.PATH, "get");
  if (params) {
    rb.path("vendor_id", params.vendor_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<VendorSpend>;
      }),
    );
}

getVendorSpend.PATH = "/api/vendors/{vendor_id}/spend";
