/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { VendorPage } from "../../models/vendor-page";

export interface ListVendors$Params {
  /**
   * Match part of the name
   */
  search?: string | null;

  /**
   * Include archived vendors
   */
  include_archived?: boolean;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listVendors(
  http: HttpClient,
  rootUrl: string,
  params?: ListVendors$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VendorPage>> {
  const rb = new RequestBuilder(rootUrl, listVendors.PATH, "get");
  if (params) {
    rb.query("search", params.search, {});
    rb.query("include_archived", params.include_archived, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<VendorPage>;
      }),
    );
}

listVendors.PATH = "/api/vendors";
