/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { VendorRead } from "../../models/vendor-read";
import { VendorUpdate } from "../../models/vendor-update";

export interface UpdateVendor$Params {
  vendor_id: string;
  body: VendorUpdate;
}

export function updateVendor(
  http: HttpClient,
  rootUrl: string,
  params: UpdateVendor$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<VendorRead>> {
  const rb = new RequestBuilder(rootUrl, updateVendor.PATH, "patch");
  if (params) {
    rb.path("vendor_id", params.vendor_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<VendorRead>;
      }),
    );
}

updateVendor.PATH = "/api/vendors/{vendor_id}";
