"""Tortoise migrations for the models app.

Migration files are generated by the migration CLI built into Tortoise, not by
Aerich. Drive it through the Makefile: `make migration name=<name>` writes a
new one, `make migrate` applies what is pending, and `make downgrade` rolls
back the last step. Migrations are applied on start as well.
"""
