/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { SearchResults } from "../../models/search-results";

export interface Search$Params {
  /**
   * What to look for
   */
  q?: string;

  /**
   * Rows per kind
   */
  limit?: number;
}

export function search(
  http: HttpClient,
  rootUrl: string,
  params?: Search$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<SearchResults>> {
  const rb = new RequestBuilder(rootUrl, search.PATH, "get");
  if (params) {
    rb.query("q", params.q, {});
    rb.query("limit", params.limit, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<SearchResults>;
      }),
    );
}

search.PATH = "/api/search";
