/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { AdvanceCreate } from "../../models/advance-create";
import { AdvanceRead } from "../../models/advance-read";

export interface AddAdvance$Params {
  project_id: string;
  body: AdvanceCreate;
}

export function addAdvance(
  http: HttpClient,
  rootUrl: string,
  params: AddAdvance$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AdvanceRead>> {
  const rb = new RequestBuilder(rootUrl, addAdvance.PATH, "post");
  if (params) {
    rb.path("project_id", params.project_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<AdvanceRead>;
      }),
    );
}

addAdvance.PATH = "/api/projects/{project_id}/advances";
