/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { PersonBalance } from "../../models/person-balance";

export interface ListBalances$Params {
  project_id: string;
}

export function listBalances(
  http: HttpClient,
  rootUrl: string,
  params: ListBalances$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<PersonBalance>>> {
  const rb = new RequestBuilder(rootUrl, listBalances.PATH, "get");
  if (params) {
    rb.path("project_id", params.project_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<PersonBalance>>;
      }),
    );
}

listBalances.PATH = "/api/projects/{project_id}/balances";
