/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { AgreementPage } from "../../models/agreement-page";

export interface ListAgreements$Params {
  project_id: string;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listAgreements(
  http: HttpClient,
  rootUrl: string,
  params: ListAgreements$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AgreementPage>> {
  const rb = new RequestBuilder(rootUrl, listAgreements.PATH, "get");
  if (params) {
    rb.path("project_id", params.project_id, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<AgreementPage>;
      }),
    );
}

listAgreements.PATH = "/api/projects/{project_id}/agreements";
