/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { AgreementRead } from "../../models/agreement-read";
import { AgreementUpdate } from "../../models/agreement-update";

export interface UpdateAgreement$Params {
  agreement_id: string;
  body: AgreementUpdate;
}

export function updateAgreement(
  http: HttpClient,
  rootUrl: string,
  params: UpdateAgreement$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AgreementRead>> {
  const rb = new RequestBuilder(rootUrl, updateAgreement.PATH, "patch");
  if (params) {
    rb.path("agreement_id", params.agreement_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<AgreementRead>;
      }),
    );
}

updateAgreement.PATH = "/api/agreements/{agreement_id}";
