/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { AdvanceRead } from "../../models/advance-read";
import { AdvanceUpdate } from "../../models/advance-update";

export interface UpdateAdvance$Params {
  advance_id: string;
  body: AdvanceUpdate;
}

export function updateAdvance(
  http: HttpClient,
  rootUrl: string,
  params: UpdateAdvance$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AdvanceRead>> {
  const rb = new RequestBuilder(rootUrl, updateAdvance.PATH, "patch");
  if (params) {
    rb.path("advance_id", params.advance_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<AdvanceRead>;
      }),
    );
}

updateAdvance.PATH = "/api/advances/{advance_id}";
