/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdvanceRead } from "../models/advance-read";
export interface AdvancePage {
  items: Array<AdvanceRead>;
  limit: number;
  offset: number;
  total: number;
}
