/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdvanceCreate {
  /**
   * Minor units of the project currency
   */
  amount: number;

  /**
   * Defaults to today
   */
  given_on?: string | null;
  notes?: string | null;
  person_id: string;
}
