/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdvanceRead {
  amount: number;
  created_at: string;
  deleted_at: string | null;
  given_on: string;
  id: string;
  notes: string | null;
  person_id: string;
  person_name: string;
  project_id: string;
  updated_at: string;
}
