/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgreementUpdate {
  agreed_amount?: number | null;
  description?: string | null;
  notes?: string | null;
}
