/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgreementCreate {
  /**
   * Minor units of the project currency
   */
  agreed_amount: number;
  description: string;
  notes?: string | null;
  vendor_id: string;
}
