/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgreementRead {
  agreed_amount: number;
  balance_amount: number;
  created_at: string;
  deleted_at: string | null;
  description: string;
  id: string;
  notes: string | null;
  paid_amount: number;
  project_id: string;
  updated_at: string;
  vendor_id: string;
  vendor_name: string;
}
