/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgreementRead } from "../models/agreement-read";
export interface AgreementPage {
  items: Array<AgreementRead>;
  limit: number;
  offset: number;
  total: number;
}
