/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentRead } from "../models/attachment-read";
export interface AttachmentPage {
  items: Array<AttachmentRead>;
  limit: number;
  offset: number;
  total: number;
}
