/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AttachmentRead {
  byte_size: number;
  checksum: string;
  content_type: string;
  created_at: string;
  deleted_at: string | null;
  expense_id: string;
  filename: string;
  id: string;
  project_id: string;
  updated_at: string;
}
