/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponse } from "../models/user-response";
export interface AuthStatus {
  is_authenticated: boolean;
  is_setup: boolean;
  user: UserResponse | null;
}
