/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JsonValue } from "../models/json-value";
export interface Backup {
  /**
   * The Setout that wrote it
   */
  app_version: string;
  exported_at: string;

  /**
   * The layout of this file. Bumped when it changes
   */
  format: number;

  /**
   * The schema the rows came out of
   */
  migration: string | null;

  /**
   * Rows per table, for reading at a glance
   */
  row_counts: {
    [key: string]: number;
  };
  tables: {
    [key: string]: Array<{
      [key: string]: JsonValue;
    }>;
  };
}
