/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BodyRunImport {
  create_missing_scopes?: boolean;
  currency_code?: string;

  /**
   * The .xlsx or .csv to read
   */
  file: string;
  name?: string;
  project_id?: string | null;
  several_codes?: string;
  skip_duplicates?: boolean;
  take_unpaid?: boolean;
}
