/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BodyPreviewImport {
  /**
   * Currency for a new project
   */
  currency_code?: string;

  /**
   * The .xlsx or .csv to read
   */
  file: string;

  /**
   * Name for a new project
   */
  name?: string;

  /**
   * Leave out to start a project
   */
  project_id?: string | null;
}
