/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CostType } from "../models/cost-type";
export interface BudgetItemCreate {
  cost_type?: CostType | null;
  description: string;

  /**
   * Minor units of the project currency
   */
  planned_amount: number;
}
