/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CostType } from "../models/cost-type";
export interface BudgetItemUpdate {
  cost_type?: CostType | null;
  description?: string | null;
  planned_amount?: number | null;
}
