/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CostType } from "../models/cost-type";
export interface BudgetItemRead {
  cost_type: CostType | null;
  created_at: string;
  deleted_at: string | null;
  description: string;
  id: string;
  planned_amount: number;
  scope_id: string;
  set_at: string;
  updated_at: string;
}
