/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetItemRead } from "../models/budget-item-read";
export interface BudgetItemPage {
  items: Array<BudgetItemRead>;
  limit: number;
  offset: number;
  total: number;
}
