/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CostType } from "./cost-type";

/**
 * Each possible value of `CostType`
 */
export const COST_TYPE: CostType[] = ["labour", "material", "fixed"];
