/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Counts {
  /**
   * Not counting archived ones
   */
  items: number;

  /**
   * Not counting archived ones
   */
  people: number;

  /**
   * Not counting deleted ones
   */
  projects: number;

  /**
   * Not counting archived ones
   */
  vendors: number;
}
