/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DecisionKind } from "./decision-kind";

/**
 * Each possible value of `DecisionKind`
 */
export const DECISION_KIND: DecisionKind[] = [
  "new_scopes",
  "several_codes",
  "unpaid",
  "no_description",
  "above_any_scope",
  "owed_not_importable",
  "duplicates",
];
