/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DecisionKind } from "../models/decision-kind";
export interface Decision {
  amount?: number;
  blocking?: boolean;
  count: number;
  detail: string;
  kind: DecisionKind;
}
