/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type DecisionKind =
  | "new_scopes"
  | "several_codes"
  | "unpaid"
  | "no_description"
  | "above_any_scope"
  | "owed_not_importable"
  | "duplicates";
