/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeliveryCreate {
  /**
   * What is owed. Defaults to the expense description
   */
  description?: string | null;
  expense_id: string;

  /**
   * When it was promised, in words
   */
  promised?: string | null;
}
