/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeliveryRead } from "../models/delivery-read";
export interface DeliveryPage {
  items: Array<DeliveryRead>;
  limit: number;
  offset: number;

  /**
   * Still owed across every matching row, in one project's currency
   */
  owed_amount: number;
  total: number;
}
