/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeliveryRead {
  /**
   * Read from the expense that paid for it
   */
  amount: number;
  created_at: string;
  currency_code: string;
  currency_exponent: number;
  deleted_at: string | null;
  description: string;
  expense_id: string;
  id: string;
  project_id: string;
  promised: string | null;
  received_at: string | null;
  spent_on: string;
  updated_at: string;
  vendor_id: string | null;
  vendor_name: string | null;
}
