/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseRead } from "../models/expense-read";
export interface ExpensePage {
  items: Array<ExpenseRead>;
  limit: number;
  offset: number;
  total: number;
}
