/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CostType } from "../models/cost-type";
export interface ExpenseRead {
  agreement_id: string | null;
  amount: number;

  /**
   * How many files are kept beside it
   */
  attachment_count: number;
  cost_type: CostType | null;
  created_at: string;
  deleted_at: string | null;
  description: string;
  id: string;
  item_id: string | null;
  notes: string | null;
  paid_by_id: string | null;
  project_id: string;
  quantity: string | null;
  scope_id: string | null;
  spent_on: string;
  unit_rate: number | null;
  updated_at: string;
  vendor_id: string | null;
}
