/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CostType } from "../models/cost-type";
export interface ExpenseUpdate {
  agreement_id?: string | null;
  amount?: number | null;
  cost_type?: CostType | null;
  description?: string | null;
  item_id?: string | null;
  notes?: string | null;
  paid_by_id?: string | null;
  quantity?: number | string | null;
  scope_id?: string | null;
  spent_on?: string | null;
  unit_rate?: number | null;
  vendor_id?: string | null;
}
