/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CostType } from "../models/cost-type";
export interface ExpenseCreate {
  /**
   * A part payment against what was agreed
   */
  agreement_id?: string | null;

  /**
   * Minor units. Derived when both quantity and unit rate are given
   */
  amount?: number | null;
  cost_type?: CostType | null;
  description: string;

  /**
   * What was bought, to build its price history
   */
  item_id?: string | null;
  notes?: string | null;

  /**
   * Who handed over the money
   */
  paid_by_id?: string | null;
  quantity?: number | string | null;

  /**
   * Leave empty to file it later
   */
  scope_id?: string | null;

  /**
   * Defaults to today
   */
  spent_on?: string | null;

  /**
   * Minor units
   */
  unit_rate?: number | null;

  /**
   * Who it was bought from
   */
  vendor_id?: string | null;
}
