/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Hit } from "../models/hit";
import { SearchKind } from "../models/search-kind";
export interface HitGroup {
  hits: Array<Hit>;
  kind: SearchKind;

  /**
   * Everything that matched, not only what is listed
   */
  total: number;
}
