/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Hit {
  amount?: number | null;
  currency_code?: string | null;
  currency_exponent?: number | null;
  detail: string;
  id: string;
  project_id?: string | null;
  spent_on?: string | null;
  title: string;
}
