/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HomeProject {
  currency_code: string;
  currency_exponent: number;
  expense_count: number;
  id: string;
  name: string;
  planned_amount: number;
  spent_amount: number;
}
