/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HomeSpend {
  amount: number;
  currency_code: string;
  currency_exponent: number;
  description: string;
  id: string;
  project_id: string;
  project_name: string;
  scope_name: string | null;
  spent_on: string;
}
