/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HomeMonth } from "../models/home-month";
export interface HomeMonths {
  busiest_month: string | null;
  currency_code: string | null;
  currency_exponent: number | null;
  months: Array<HomeMonth>;
}
