/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyChoice } from "../models/currency-choice";
import { HomeAlert } from "../models/home-alert";

/**
 * The figures for one currency. Nothing here is ever added across two.
 */
export interface HomeSummary {
  alerts: Array<HomeAlert>;
  currencies: Array<CurrencyChoice>;
  currency_code: string | null;
  currency_exponent: number | null;

  /**
   * Projects kept in this currency
   */
  currency_projects?: number;
  planned_amount: number;

  /**
   * Every project, whatever its currency
   */
  projects: number;
  spent_amount: number;
}
