/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Decision } from "../models/decision";
import { SampleRow } from "../models/sample-row";
import { ScopeMatch } from "../models/scope-match";
import { SheetSeen } from "../models/sheet-seen";
import { SheetSkipped } from "../models/sheet-skipped";
export interface ImportReport {
  currency_code: string;
  currency_exponent: number;
  decisions: Array<Decision>;

  /**
   * Columns the sheet holds that Setout keeps nowhere
   */
  left_behind: Array<string>;
  owed_rows: number;
  planned_amount: number;
  planned_lines: number;
  project_id: string | null;
  project_name: string;
  read: Array<SheetSeen>;

  /**
   * The first spend rows as they would be filed
   */
  sample: Array<SampleRow>;
  scopes: Array<ScopeMatch>;
  skipped: Array<SheetSkipped>;
  spend_amount: number;
  spend_rows: number;
  vendors_known: number;
  vendors_new: number;
}
