/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Install {
  /**
   * The last schema change applied to this record
   */
  migration: string | null;

  /**
   * Everything under the data directory, added up
   */
  record_bytes: number;

  /**
   * When anything under the data directory was last written
   */
  record_changed_at: string | null;
  version: string;
}
