/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemLastPrice } from "../models/item-last-price";
export interface ItemLastPriceResponse {
  item_id: string;

  /**
   * Null when nothing has been bought yet in this project's currency
   */
  last_price: ItemLastPrice | null;
  project_id: string;
}
