/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemLastPrice {
  currency_code: string;
  currency_exponent: number;
  item_id: string;
  project_id: string;
  project_name: string;
  spent_on: string;
  unit_rate: number;
  vendor_id: string | null;
  vendor_name: string | null;
}
