/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemRead } from "../models/item-read";
export interface ItemPage {
  items: Array<ItemRead>;
  limit: number;
  offset: number;
  total: number;
}
