/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemPriceSeries } from "../models/item-price-series";
export interface ItemPrices {
  item_id: string;
  name: string;

  /**
   * One series per currency. Prices are never compared across currencies
   */
  series: Array<ItemPriceSeries>;
  unit: string | null;
}
