/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemPricePoint } from "../models/item-price-point";
export interface ItemPriceSeries {
  /**
   * Null when there is only one price, so nothing to compare
   */
  change_percent: number | null;
  count: number;
  currency_code: string;
  currency_exponent: number;
  first_paid_on: string;
  first_price: number;
  highest_price: number;
  last_paid_on: string;
  last_price: number;
  lowest_price: number;
  points: Array<ItemPricePoint>;
}
