/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemPricePoint {
  expense_id: string;
  project_id: string;
  project_name: string;
  quantity: string | null;
  spent_on: string;

  /**
   * Price for one unit, in minor units
   */
  unit_rate: number;
  vendor_id: string | null;
  vendor_name: string | null;
}
