/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemPriceSummary } from "../models/item-price-summary";
export interface ItemRead {
  created_at: string;
  deleted_at: string | null;
  id: string;
  name: string;
  notes: string | null;

  /**
   * One entry per currency. Prices are never compared across currencies
   */
  prices: Array<ItemPriceSummary>;
  purchase_count: number;
  unit: string | null;
  updated_at: string;
}
