/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemCreate {
  name: string;
  notes?: string | null;

  /**
   * What the price is quoted in
   */
  unit?: string | null;
}
