/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MonthScopeSpend } from "../models/month-scope-spend";
export interface MonthSpend {
  amount: number;
  expense_count: number;

  /**
   * Calendar month as YYYY-MM
   */
  month: string;

  /**
   * Split by the scope at the top of each branch, in budget order
   */
  scopes: Array<MonthScopeSpend>;
}
