/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MonthScopeSpend {
  amount: number;
  name: string;

  /**
   * Null for spend that reached no scope
   */
  scope_id: string | null;
}
