/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PasswordChange {
  /**
   * The passphrase in use now
   */
  current_password: string;
  new_password: string;
}
