/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonCurrencyTotal } from "../models/person-currency-total";
export interface PersonRead {
  created_at: string;
  deleted_at: string | null;
  expense_count: number;
  id: string;
  name: string;
  notes: string | null;
  phone: string | null;
  role: string | null;

  /**
   * One entry per currency. Two currencies are never added together
   */
  totals: Array<PersonCurrencyTotal>;
  updated_at: string;
}
