/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonProjectSpend {
  currency_code: string;
  currency_exponent: number;
  expense_count: number;
  project_id: string;
  project_name: string;
  spent_amount: number;
}
