/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonRead } from "../models/person-read";
export interface PersonPage {
  items: Array<PersonRead>;
  limit: number;
  offset: number;
  total: number;
}
