/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonUpdate {
  name?: string | null;
  notes?: string | null;
  phone?: string | null;
  role?: string | null;
}
