/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonProjectSpend } from "../models/person-project-spend";
export interface PersonSpend {
  name: string;
  person_id: string;

  /**
   * What they spent, per project. Two currencies are never added together
   */
  projects: Array<PersonProjectSpend>;
}
