/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonBalance {
  advanced_amount: number;
  balance_amount: number;
  currency_code: string;
  currency_exponent: number;
  person_id: string;
  person_name: string;
  project_id: string;
  spent_amount: number;
}
