/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectStatus } from "../models/project-status";
export interface ProjectCreate {
  /**
   * ISO 4217 code. Fixed once the project exists
   */
  currency_code: string;
  name: string;
  notes?: string | null;
  status?: ProjectStatus;
}
