/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectSpend {
  currency_code: string;
  currency_exponent: number;
  planned_amount: number;
  project_id: string;

  /**
   * Expenses taken off the record, in no total
   */
  removed_count: number;
  spent_amount: number;
  unfiled_amount: number;
  unfiled_count: number;

  /**
   * Null when there is no budget to compare against, never infinity
   */
  variance_percent: number | null;
}
