/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectSummary {
  active: number;
  archived: number;
  completed: number;
  currency_codes: Array<string>;
  deleted: number;
  on_hold: number;
  total: number;
}
