/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MonthSpend } from "../models/month-spend";
export interface ProjectMonths {
  /**
   * Null until something has been spent
   */
  busiest_month: string | null;
  currency_code: string;
  currency_exponent: number;

  /**
   * Oldest first. A month with nothing spent in it is left out
   */
  months: Array<MonthSpend>;
  project_id: string;
  total_amount: number;
}
