/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectStatus } from "./project-status";

/**
 * Each possible value of `ProjectStatus`
 */
export const PROJECT_STATUS: ProjectStatus[] = [
  "active",
  "on_hold",
  "completed",
  "archived",
];
