/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectStatus } from "../models/project-status";
export interface ProjectRead {
  created_at: string;
  currency_code: string;
  currency_exponent: number;
  deleted_at: string | null;
  id: string;
  name: string;
  notes: string | null;
  planned_amount: number;
  spent_amount: number;
  status: ProjectStatus;
  updated_at: string;
}
