/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScopeRead } from "../models/scope-read";
export interface ProjectBudget {
  currency_code: string;
  currency_exponent: number;
  planned_amount: number;
  project_id: string;
  scopes: Array<ScopeRead>;
}
