/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectRead } from "../models/project-read";
export interface ProjectPage {
  items: Array<ProjectRead>;
  limit: number;
  offset: number;
  total: number;
}
