/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Backup } from "../models/backup";
export interface RestoreRequest {
  /**
   * Required when the file was written by a different Setout or schema
   */
  accept_version_change?: boolean;
  backup: Backup;
}
