/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScopeMatch {
  code: string;
  lines: number;

  /**
   * Name of the scope already here, if any
   */
  matched_to?: string | null;
  name: string;
  planned_amount: number;
}
