/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScopeRead {
  code: string | null;
  created_at: string;
  deleted_at: string | null;
  expense_count: number;
  id: string;
  is_group: boolean;
  name: string;
  own_expense_count: number;
  own_planned_amount: number;
  own_spent_amount: number;
  parent_id: string | null;
  planned_amount: number;
  project_id: string;
  sort_order: number;
  spent_amount: number;
  updated_at: string;
}
