/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScopeUpdate {
  code?: string | null;
  name?: string | null;
  parent_id?: string | null;
  sort_order?: number | null;
}
