/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchKind } from "./search-kind";

/**
 * Each possible value of `SearchKind`
 */
export const SEARCH_KIND: SearchKind[] = [
  "projects",
  "expenses",
  "vendors",
  "people",
  "items",
];
