/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SetupRequest {
  /**
   * Optional. Only used to identify the account
   */
  email?: string | null;

  /**
   * The local account name
   */
  name: string;
  password: string;
}
