/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VendorUpdate {
  contact_name?: string | null;
  email?: string | null;
  name?: string | null;
  notes?: string | null;
  phone?: string | null;
  trade?: string | null;
}
