/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VendorRead } from "../models/vendor-read";
export interface VendorPage {
  items: Array<VendorRead>;
  limit: number;
  offset: number;
  total: number;
}
