/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VendorProjectSpend } from "../models/vendor-project-spend";
export interface VendorSpend {
  name: string;

  /**
   * One row per project. Two currencies are never added together
   */
  projects: Array<VendorProjectSpend>;
  vendor_id: string;
}
