/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VendorAgreement {
  agreed_amount: number;
  balance_amount: number;
  created_at: string;
  currency_code: string;
  currency_exponent: number;
  deleted_at: string | null;
  description: string;
  id: string;
  paid_amount: number;
  project_id: string;
  project_name: string;
}
