/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VendorCurrencyTotal } from "../models/vendor-currency-total";
export interface VendorRead {
  contact_name: string | null;
  created_at: string;
  deleted_at: string | null;
  email: string | null;
  expense_count: number;
  id: string;
  name: string;
  notes: string | null;
  phone: string | null;

  /**
   * One entry per currency. Two currencies are never added together
   */
  totals: Array<VendorCurrencyTotal>;
  trade: string | null;
  updated_at: string;
}
