/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VendorCreate {
  contact_name?: string | null;
  email?: string | null;
  name: string;
  notes?: string | null;
  phone?: string | null;
  trade?: string | null;
}
