/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VendorAgreement } from "../models/vendor-agreement";
export interface VendorAgreements {
  /**
   * Across every project, newest first. Currencies are never added together
   */
  agreements: Array<VendorAgreement>;
  name: string;
  vendor_id: string;
}
