/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VendorCurrencyTotal {
  currency_code: string;
  currency_exponent: number;
  expense_count: number;
  spent_amount: number;
}
