/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { AttachmentRead } from "../../models/attachment-read";
import { BodyAddAttachment } from "../../models/body-add-attachment";

export interface AddAttachment$Params {
  project_id: string;
  expense_id: string;
  body: BodyAddAttachment;
}

export function addAttachment(
  http: HttpClient,
  rootUrl: string,
  params: AddAttachment$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AttachmentRead>> {
  const rb = new RequestBuilder(rootUrl, addAttachment.PATH, "post");
  if (params) {
    rb.path("project_id", params.project_id, {});
    rb.path("expense_id", params.expense_id, {});
    rb.body(params.body, "multipart/form-data");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<AttachmentRead>;
      }),
    );
}

addAttachment.PATH =
  "/api/projects/{project_id}/expenses/{expense_id}/attachments";
