/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

export interface DownloadAttachment$Params {
  attachment_id: string;
}

export function downloadAttachment(
  http: HttpClient,
  rootUrl: string,
  params: DownloadAttachment$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, downloadAttachment.PATH, "get");
  if (params) {
    rb.path("attachment_id", params.attachment_id, {});
  }

  return http
    .request(
      rb.build({
        responseType: "blob",
        accept: "application/octet-stream",
        context,
      }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Blob>;
      }),
    );
}

downloadAttachment.PATH = "/api/attachments/{attachment_id}/file";
