/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { AttachmentPage } from "../../models/attachment-page";

export interface ListAttachments$Params {
  expense_id: string;

  /**
   * Include removed files
   */
  include_deleted?: boolean;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listAttachments(
  http: HttpClient,
  rootUrl: string,
  params: ListAttachments$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AttachmentPage>> {
  const rb = new RequestBuilder(rootUrl, listAttachments.PATH, "get");
  if (params) {
    rb.path("expense_id", params.expense_id, {});
    rb.query("include_deleted", params.include_deleted, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<AttachmentPage>;
      }),
    );
}

listAttachments.PATH = "/api/expenses/{expense_id}/attachments";
