/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ExpensePage } from "../../models/expense-page";

export interface ListExpenses$Params {
  project_id: string;

  /**
   * Only this scope
   */
  scope_id?: string | null;

  /**
   * Only payments on this agreement
   */
  agreement_id?: string | null;

  /**
   * Only this calendar month, as YYYY-MM
   */
  month?: string | null;

  /**
   * Only spend with no scope
   */
  unfiled_only?: boolean;

  /**
   * Only payments filed against some agreement
   */
  agreement_only?: boolean;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listExpenses(
  http: HttpClient,
  rootUrl: string,
  params: ListExpenses$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ExpensePage>> {
  const rb = new RequestBuilder(rootUrl, listExpenses.PATH, "get");
  if (params) {
    rb.path("project_id", params.project_id, {});
    rb.query("scope_id", params.scope_id, {});
    rb.query("agreement_id", params.agreement_id, {});
    rb.query("month", params.month, {});
    rb.query("unfiled_only", params.unfiled_only, {});
    rb.query("agreement_only", params.agreement_only, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ExpensePage>;
      }),
    );
}

listExpenses.PATH = "/api/projects/{project_id}/expenses";
