/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ExpenseRead } from "../../models/expense-read";
import { ExpenseUpdate } from "../../models/expense-update";

export interface UpdateExpense$Params {
  expense_id: string;
  body: ExpenseUpdate;
}

export function updateExpense(
  http: HttpClient,
  rootUrl: string,
  params: UpdateExpense$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ExpenseRead>> {
  const rb = new RequestBuilder(rootUrl, updateExpense.PATH, "patch");
  if (params) {
    rb.path("expense_id", params.expense_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ExpenseRead>;
      }),
    );
}

updateExpense.PATH = "/api/expenses/{expense_id}";
