/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { HomeSummary } from "../../models/home-summary";

export interface GetHomeSummary$Params {
  /**
   * Which currency to read. Falls back to the account's, then the first in use
   */
  currency?: string | null;
}

export function getHomeSummary(
  http: HttpClient,
  rootUrl: string,
  params?: GetHomeSummary$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<HomeSummary>> {
  const rb = new RequestBuilder(rootUrl, getHomeSummary.PATH, "get");
  if (params) {
    rb.query("currency", params.currency, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<HomeSummary>;
      }),
    );
}

getHomeSummary.PATH = "/api/home/summary";
