/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

export interface ExportProject$Params {
  project_id: string;
}

export function exportProject(
  http: HttpClient,
  rootUrl: string,
  params: ExportProject$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, exportProject.PATH, "get");
  if (params) {
    rb.path("project_id", params.project_id, {});
  }

  return http
    .request(
      rb.build({
        responseType: "blob",
        accept:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        context,
      }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Blob>;
      }),
    );
}

exportProject.PATH = "/api/projects/{project_id}/export";
