/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

export interface ImportSample$Params {
  /**
   * An empty workbook, one with rows to copy, or either sheet as a CSV
   */
  kind?: string;
}

export function importSample(
  http: HttpClient,
  rootUrl: string,
  params?: ImportSample$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, importSample.PATH, "get");
  if (params) {
    rb.query("kind", params.kind, {});
  }

  return http
    .request(
      rb.build({
        responseType: "blob",
        accept:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        context,
      }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Blob>;
      }),
    );
}

importSample.PATH = "/api/import/sample";
