/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { BodyPreviewImport } from "../../models/body-preview-import";
import { ImportReport } from "../../models/import-report";

export interface PreviewImport$Params {
  body: BodyPreviewImport;
}

export function previewImport(
  http: HttpClient,
  rootUrl: string,
  params: PreviewImport$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ImportReport>> {
  const rb = new RequestBuilder(rootUrl, previewImport.PATH, "post");
  if (params) {
    rb.body(params.body, "multipart/form-data");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ImportReport>;
      }),
    );
}

previewImport.PATH = "/api/import/preview";
