/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { BodyRunImport } from "../../models/body-run-import";
import { ImportResult } from "../../models/import-result";

export interface RunImport$Params {
  body: BodyRunImport;
}

export function runImport(
  http: HttpClient,
  rootUrl: string,
  params: RunImport$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ImportResult>> {
  const rb = new RequestBuilder(rootUrl, runImport.PATH, "post");
  if (params) {
    rb.body(params.body, "multipart/form-data");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ImportResult>;
      }),
    );
}

runImport.PATH = "/api/import";
