/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { SetupRequest } from "../../models/setup-request";
import { UserResponse } from "../../models/user-response";

export interface SetupAdmin$Params {
  body: SetupRequest;
}

export function setupAdmin(
  http: HttpClient,
  rootUrl: string,
  params: SetupAdmin$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, setupAdmin.PATH, "post");
  if (params) {
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<UserResponse>;
      }),
    );
}

setupAdmin.PATH = "/api/auth/setup";
