/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ProjectRead } from "../../models/project-read";

export interface GetProject$Params {
  project_id: string;
}

export function getProject(
  http: HttpClient,
  rootUrl: string,
  params: GetProject$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ProjectRead>> {
  const rb = new RequestBuilder(rootUrl, getProject.PATH, "get");
  if (params) {
    rb.path("project_id", params.project_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ProjectRead>;
      }),
    );
}

getProject.PATH = "/api/projects/{project_id}";
