/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ProjectPage } from "../../models/project-page";

export interface ListProjects$Params {
  /**
   * Include soft deleted projects
   */
  include_deleted?: boolean;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listProjects(
  http: HttpClient,
  rootUrl: string,
  params?: ListProjects$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ProjectPage>> {
  const rb = new RequestBuilder(rootUrl, listProjects.PATH, "get");
  if (params) {
    rb.query("include_deleted", params.include_deleted, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ProjectPage>;
      }),
    );
}

listProjects.PATH = "/api/projects";
