/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ProjectRead } from "../../models/project-read";

export interface RestoreProject$Params {
  project_id: string;
}

export function restoreProject(
  http: HttpClient,
  rootUrl: string,
  params: RestoreProject$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ProjectRead>> {
  const rb = new RequestBuilder(rootUrl, restoreProject.PATH, "post");
  if (params) {
    rb.path("project_id", params.project_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ProjectRead>;
      }),
    );
}

restoreProject.PATH = "/api/projects/{project_id}/restore";
