/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { PersonRead } from "../../models/person-read";
import { PersonUpdate } from "../../models/person-update";

export interface UpdatePerson$Params {
  person_id: string;
  body: PersonUpdate;
}

export function updatePerson(
  http: HttpClient,
  rootUrl: string,
  params: UpdatePerson$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PersonRead>> {
  const rb = new RequestBuilder(rootUrl, updatePerson.PATH, "patch");
  if (params) {
    rb.path("person_id", params.person_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<PersonRead>;
      }),
    );
}

updatePerson.PATH = "/api/people/{person_id}";
