/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { Backup } from "../../models/backup";

export interface ExportRecord$Params {}

export function exportRecord(
  http: HttpClient,
  rootUrl: string,
  params?: ExportRecord$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Backup>> {
  const rb = new RequestBuilder(rootUrl, exportRecord.PATH, "get");
  if (params) {
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Backup>;
      }),
    );
}

exportRecord.PATH = "/api/install/export";
