/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { DeliveryPage } from "../../models/delivery-page";

export interface ListAllDeliveries$Params {
  /**
   * Only this vendor
   */
  vendor_id?: string | null;

  /**
   * Only what has not arrived
   */
  outstanding_only?: boolean;

  /**
   * Only what has arrived
   */
  received_only?: boolean;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listAllDeliveries(
  http: HttpClient,
  rootUrl: string,
  params?: ListAllDeliveries$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<DeliveryPage>> {
  const rb = new RequestBuilder(rootUrl, listAllDeliveries.PATH, "get");
  if (params) {
    rb.query("vendor_id", params.vendor_id, {});
    rb.query("outstanding_only", params.outstanding_only, {});
    rb.query("received_only", params.received_only, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<DeliveryPage>;
      }),
    );
}

listAllDeliveries.PATH = "/api/deliveries";
