/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { DeliveryRead } from "../../models/delivery-read";

export interface RestoreDelivery$Params {
  delivery_id: string;
}

export function restoreDelivery(
  http: HttpClient,
  rootUrl: string,
  params: RestoreDelivery$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<DeliveryRead>> {
  const rb = new RequestBuilder(rootUrl, restoreDelivery.PATH, "post");
  if (params) {
    rb.path("delivery_id", params.delivery_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<DeliveryRead>;
      }),
    );
}

restoreDelivery.PATH = "/api/deliveries/{delivery_id}/restore";
