/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { DeliveryRead } from "../../models/delivery-read";
import { DeliveryUpdate } from "../../models/delivery-update";

export interface UpdateDelivery$Params {
  delivery_id: string;
  body: DeliveryUpdate;
}

export function updateDelivery(
  http: HttpClient,
  rootUrl: string,
  params: UpdateDelivery$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<DeliveryRead>> {
  const rb = new RequestBuilder(rootUrl, updateDelivery.PATH, "patch");
  if (params) {
    rb.path("delivery_id", params.delivery_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<DeliveryRead>;
      }),
    );
}

updateDelivery.PATH = "/api/deliveries/{delivery_id}";
