/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { BudgetItemCreate } from "../../models/budget-item-create";
import { BudgetItemRead } from "../../models/budget-item-read";

export interface AddBudgetItem$Params {
  scope_id: string;
  body: BudgetItemCreate;
}

export function addBudgetItem(
  http: HttpClient,
  rootUrl: string,
  params: AddBudgetItem$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BudgetItemRead>> {
  const rb = new RequestBuilder(rootUrl, addBudgetItem.PATH, "post");
  if (params) {
    rb.path("scope_id", params.scope_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<BudgetItemRead>;
      }),
    );
}

addBudgetItem.PATH = "/api/scopes/{scope_id}/budget-items";
