/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ScopeCreate } from "../../models/scope-create";
import { ScopeRead } from "../../models/scope-read";

export interface CreateScope$Params {
  project_id: string;
  body: ScopeCreate;
}

export function createScope(
  http: HttpClient,
  rootUrl: string,
  params: CreateScope$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ScopeRead>> {
  const rb = new RequestBuilder(rootUrl, createScope.PATH, "post");
  if (params) {
    rb.path("project_id", params.project_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ScopeRead>;
      }),
    );
}

createScope.PATH = "/api/projects/{project_id}/scopes";
