/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

export interface DeleteBudgetItem$Params {
  item_id: string;
}

export function deleteBudgetItem(
  http: HttpClient,
  rootUrl: string,
  params: DeleteBudgetItem$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteBudgetItem.PATH, "delete");
  if (params) {
    rb.path("item_id", params.item_id, {});
  }

  return http
    .request(rb.build({ responseType: "text", accept: "*/*", context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return (r as HttpResponse<any>).clone({
          body: undefined,
        }) as StrictHttpResponse<void>;
      }),
    );
}

deleteBudgetItem.PATH = "/api/budget-items/{item_id}";
