/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ScopePresetRead } from "../../models/scope-preset-read";

export interface ListScopePresets$Params {}

export function listScopePresets(
  http: HttpClient,
  rootUrl: string,
  params?: ListScopePresets$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<ScopePresetRead>>> {
  const rb = new RequestBuilder(rootUrl, listScopePresets.PATH, "get");
  if (params) {
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<ScopePresetRead>>;
      }),
    );
}

listScopePresets.PATH = "/api/scope-presets";
