/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ScopeRead } from "../../models/scope-read";

export interface ListScopes$Params {
  project_id: string;
}

export function listScopes(
  http: HttpClient,
  rootUrl: string,
  params: ListScopes$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<ScopeRead>>> {
  const rb = new RequestBuilder(rootUrl, listScopes.PATH, "get");
  if (params) {
    rb.path("project_id", params.project_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<ScopeRead>>;
      }),
    );
}

listScopes.PATH = "/api/projects/{project_id}/scopes";
