/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { BudgetItemPage } from "../../models/budget-item-page";

export interface ListBudgetItems$Params {
  scope_id: string;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listBudgetItems(
  http: HttpClient,
  rootUrl: string,
  params: ListBudgetItems$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BudgetItemPage>> {
  const rb = new RequestBuilder(rootUrl, listBudgetItems.PATH, "get");
  if (params) {
    rb.path("scope_id", params.scope_id, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<BudgetItemPage>;
      }),
    );
}

listBudgetItems.PATH = "/api/scopes/{scope_id}/budget-items";
