/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ScopeRead } from "../../models/scope-read";

export interface RestoreScope$Params {
  scope_id: string;
}

export function restoreScope(
  http: HttpClient,
  rootUrl: string,
  params: RestoreScope$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ScopeRead>> {
  const rb = new RequestBuilder(rootUrl, restoreScope.PATH, "post");
  if (params) {
    rb.path("scope_id", params.scope_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ScopeRead>;
      }),
    );
}

restoreScope.PATH = "/api/scopes/{scope_id}/restore";
