/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ScopeRead } from "../../models/scope-read";
import { ScopeUpdate } from "../../models/scope-update";

export interface UpdateScope$Params {
  scope_id: string;
  body: ScopeUpdate;
}

export function updateScope(
  http: HttpClient,
  rootUrl: string,
  params: UpdateScope$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ScopeRead>> {
  const rb = new RequestBuilder(rootUrl, updateScope.PATH, "patch");
  if (params) {
    rb.path("scope_id", params.scope_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ScopeRead>;
      }),
    );
}

updateScope.PATH = "/api/scopes/{scope_id}";
