/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { BudgetItemRead } from "../../models/budget-item-read";
import { BudgetItemUpdate } from "../../models/budget-item-update";

export interface UpdateBudgetItem$Params {
  item_id: string;
  body: BudgetItemUpdate;
}

export function updateBudgetItem(
  http: HttpClient,
  rootUrl: string,
  params: UpdateBudgetItem$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<BudgetItemRead>> {
  const rb = new RequestBuilder(rootUrl, updateBudgetItem.PATH, "patch");
  if (params) {
    rb.path("item_id", params.item_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<BudgetItemRead>;
      }),
    );
}

updateBudgetItem.PATH = "/api/budget-items/{item_id}";
