/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ItemCreate } from "../../models/item-create";
import { ItemRead } from "../../models/item-read";

export interface CreateItem$Params {
  body: ItemCreate;
}

export function createItem(
  http: HttpClient,
  rootUrl: string,
  params: CreateItem$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ItemRead>> {
  const rb = new RequestBuilder(rootUrl, createItem.PATH, "post");
  if (params) {
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ItemRead>;
      }),
    );
}

createItem.PATH = "/api/items";
