/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ItemLastPriceResponse } from "../../models/item-last-price-response";

export interface GetItemLastPrice$Params {
  project_id: string;
  item_id: string;
}

export function getItemLastPrice(
  http: HttpClient,
  rootUrl: string,
  params: GetItemLastPrice$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ItemLastPriceResponse>> {
  const rb = new RequestBuilder(rootUrl, getItemLastPrice.PATH, "get");
  if (params) {
    rb.path("project_id", params.project_id, {});
    rb.path("item_id", params.item_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ItemLastPriceResponse>;
      }),
    );
}

getItemLastPrice.PATH = "/api/projects/{project_id}/items/{item_id}/last-price";
