/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ItemPage } from "../../models/item-page";

export interface ListItems$Params {
  /**
   * Match part of the name
   */
  search?: string | null;

  /**
   * Rows per page
   */
  limit?: number;

  /**
   * Rows to skip
   */
  offset?: number;
}

export function listItems(
  http: HttpClient,
  rootUrl: string,
  params?: ListItems$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ItemPage>> {
  const rb = new RequestBuilder(rootUrl, listItems.PATH, "get");
  if (params) {
    rb.query("search", params.search, {});
    rb.query("limit", params.limit, {});
    rb.query("offset", params.offset, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ItemPage>;
      }),
    );
}

listItems.PATH = "/api/items";
