/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ItemRead } from "../../models/item-read";

export interface RestoreItem$Params {
  item_id: string;
}

export function restoreItem(
  http: HttpClient,
  rootUrl: string,
  params: RestoreItem$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ItemRead>> {
  const rb = new RequestBuilder(rootUrl, restoreItem.PATH, "post");
  if (params) {
    rb.path("item_id", params.item_id, {});
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ItemRead>;
      }),
    );
}

restoreItem.PATH = "/api/items/{item_id}/restore";
