/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { filter, map } from "rxjs/operators";
import { StrictHttpResponse } from "../../strict-http-response";
import { RequestBuilder } from "../../request-builder";

import { ItemRead } from "../../models/item-read";
import { ItemUpdate } from "../../models/item-update";

export interface UpdateItem$Params {
  item_id: string;
  body: ItemUpdate;
}

export function updateItem(
  http: HttpClient,
  rootUrl: string,
  params: UpdateItem$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<ItemRead>> {
  const rb = new RequestBuilder(rootUrl, updateItem.PATH, "patch");
  if (params) {
    rb.path("item_id", params.item_id, {});
    rb.body(params.body, "application/json");
  }

  return http
    .request(
      rb.build({ responseType: "json", accept: "application/json", context }),
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ItemRead>;
      }),
    );
}

updateItem.PATH = "/api/items/{item_id}";
